name: default
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy
  - scipy
  - scikit-learn
  - librosa
  - fastapi
  - uvicorn
  - matplotlib
  - pip
  - pydub
  - reportlab